#!/bin/sh
cd "$(dirname "$0")"
bazel build //:NullpoMinoSDL_deploy.jar || exit $?

export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
java -Djna.library.path=/usr/local/lib:/usr/lib/x86_64-linux-gnu -jar bazel-bin/NullpoMinoSDL_deploy.jar "$@"
