load("@rules_java//java:defs.bzl", "java_test")

java_test(
    name = "AllTests",
    srcs = glob(["**/*.java"]),
    args = [
        "execute",
        "--select-package=mu.nu.nullpo",
        "--disable-banner",
        "--fail-if-no-tests",
    ],
    data = ["//:config_files"],
    javacopts = ["-encoding", "UTF-8"],
    main_class = "org.junit.platform.console.ConsoleLauncher",
    use_testrunner = False,
    deps = [
        "//src/main/java:nullpomino",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
    ],
    runtime_deps = [
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_platform_junit_platform_console",
    ],
)
