#!/usr/bin/env python3
"""Regenerate test_map.bzl for the per-file java_test rules in BUILD.bazel.

Scans every test source for (a) references to top-level classes defined in
sibling test files of the same package -> EXTRA_SRCS (transitive closure), and
(b) files whose declared top-level classes differ from the filename-derived
class (extra classes, or none matching the filename at all) -> SELECT_CLASSES.
Run from the repo root: python3 src/test/java/gen_test_map.py
"""

import collections
import os
import re

ROOT = os.path.join(os.path.dirname(__file__))
OUT = os.path.join(ROOT, "test_map.bzl")


def main():
    files = []
    for dp, _, fns in os.walk(ROOT):
        files += [os.path.join(dp, fn) for fn in fns if fn.endswith(".java")]
    testfiles = [f for f in files if "/testutil/" not in f]
    rel = lambda f: os.path.relpath(f, ROOT)

    # Top-level classes per package dir, from declarations at column 0. A
    # file's class list may not match its filename (a package-private class
    # can live in an arbitrarily named file, e.g. TSpinAIBranchCoverageTest3
    # .java declares only TSpinAIBranchCoverageTest2), so --select-class args
    # must come from the declarations, not the filename.
    defs = collections.defaultdict(dict)  # dir -> class name -> file
    select_classes = {}
    decl = re.compile(r"^(?:public\s+|final\s+|abstract\s+)*(?:class|interface|enum)\s+(\w+)", re.M)
    testset = set(testfiles)
    for f in files:
        src = open(f, encoding="utf-8").read()
        base = os.path.basename(f)[:-5]
        pkg = os.path.dirname(rel(f)).replace("/", ".")
        declared = decl.findall(src)
        for name in declared:
            defs[os.path.dirname(f)][name] = f
        defs[os.path.dirname(f)].setdefault(base, f)
        if f in testset and declared != [base]:
            select_classes[rel(f)] = [pkg + "." + n for n in declared]

    direct = collections.defaultdict(set)
    for f in testfiles:
        src = open(f, encoding="utf-8").read()
        for name, deff in defs[os.path.dirname(f)].items():
            if deff != f and re.search(r"\b" + re.escape(name) + r"\b", src):
                direct[f].add(deff)

    def closure(f, seen):
        for d in direct.get(f, ()):
            if d not in seen:
                seen.add(d)
                closure(d, seen)
        return seen

    extra_srcs = {
        rel(f): sorted(rel(d) for d in closure(f, set()) - {f}) for f in direct
    }

    with open(OUT, "w") as out:
        out.write('"""Generated by gen_test_map.py -- do not edit by hand."""\n\n')
        for name, mapping in [("EXTRA_SRCS", extra_srcs), ("SELECT_CLASSES", select_classes)]:
            out.write("%s = {\n" % name)
            for k in sorted(mapping):
                out.write('    "%s": [\n' % k)
                for v in sorted(mapping[k]):
                    out.write('        "%s",\n' % v)
                out.write("    ],\n")
            out.write("}\n\n")
    print("wrote %s: %d EXTRA_SRCS, %d SELECT_CLASSES" % (OUT, len(extra_srcs), len(select_classes)))


if __name__ == "__main__":
    main()
