"""Generated by gen_test_map.py -- do not edit by hand."""

EXTRA_SRCS = {
    "nullpomino/game/ai/ComboRaceBotResidualBranchCoverageTest.java": [
        "nullpomino/game/ai/ComboRaceBotDeepBranchCoverageTest.java",
    ],
    "nullpomino/game/ai/NohohoStaticHelpersTest.java": [
        "nullpomino/game/ai/PoochyBotStaticHelpersTest.java",
    ],
    "nullpomino/game/ai/PoochyBotResidualBranchCoverageTest.java": [
        "nullpomino/game/ai/PoochyBotDeepBranchCoverageTest.java",
    ],
    "nullpomino/game/ai/RanksAITest.java": [
        "nullpomino/game/ai/RanksAIStaticHelpersTest.java",
    ],
    "nullpomino/game/component/FieldColorClearTest.java": [
        "nullpomino/game/component/FieldClearAndCascadeTest.java",
    ],
    "nullpomino/game/mode/AvalancheVSDummyModeLoadOtherSettingTest.java": [
        "nullpomino/game/mode/AvalancheVSDummyModeOtherSettingTest.java",
    ],
    "nullpomino/game/mode/AvalancheVSModeBranchCoverageTest.java": [
        "nullpomino/game/mode/AvalancheVSModeSettingMenuTest.java",
    ],
    "nullpomino/game/mode/AvalancheVSModeCoverageBoostTest.java": [
        "nullpomino/game/mode/AvalancheVSModeSettingMenuTest.java",
    ],
    "nullpomino/game/mode/ComboRaceModeSettingWraparoundTest.java": [
        "nullpomino/game/mode/ComboRaceModeCoverageBoostTest.java",
    ],
    "nullpomino/game/mode/GemManiaModeBranchCoverageTest.java": [
        "nullpomino/game/mode/GemManiaModeSettingWraparoundTest.java",
    ],
    "nullpomino/game/mode/GradeMania3ModeSettingWraparoundTest.java": [
        "nullpomino/game/mode/GradeMania3ModeSettingMenuTest.java",
    ],
    "nullpomino/game/mode/NetDummyVSModeBranchCoverageTest3.java": [
        "nullpomino/game/mode/NetDummyVSModeBranchCoverageTest2.java",
    ],
    "nullpomino/game/mode/NetDummyVSModeCoverageBoostTest.java": [
        "nullpomino/game/mode/NetDummyVSModeDeepCoverageTest.java",
    ],
    "nullpomino/game/mode/NetVSBattleModeConstantsTest.java": [
        "nullpomino/game/mode/NetVSLineRaceAndBattleModeInitTest.java",
    ],
    "nullpomino/game/mode/NetVSBattleModeTest.java": [
        "nullpomino/game/mode/NetVSBattleModeConstantsTest.java",
        "nullpomino/game/mode/NetVSLineRaceAndBattleModeInitTest.java",
    ],
    "nullpomino/game/mode/SPFModeBranchCoverageTest.java": [
        "nullpomino/game/mode/SPFModeSettingMenuTest.java",
    ],
    "nullpomino/game/mode/SPFModeCoverageBoostTest.java": [
        "nullpomino/game/mode/SPFModeGameLogicTest.java",
        "nullpomino/game/mode/SPFModeHelpersTest.java",
        "nullpomino/game/mode/SPFModeOtherSettingTest.java",
        "nullpomino/game/mode/SPFModeSettingMenuTest.java",
        "nullpomino/game/mode/SPFModeTest.java",
    ],
    "nullpomino/game/mode/SPFModeRemainderCoverageTest.java": [
        "nullpomino/game/mode/SPFModeCoverageBoostTest.java",
        "nullpomino/game/mode/SPFModeGameLogicTest.java",
        "nullpomino/game/mode/SPFModeHelpersTest.java",
        "nullpomino/game/mode/SPFModeOtherSettingTest.java",
        "nullpomino/game/mode/SPFModeSettingMenuTest.java",
        "nullpomino/game/mode/SPFModeTest.java",
    ],
    "nullpomino/game/mode/SpeedManiaModeTailCoverageTest2.java": [
        "nullpomino/game/mode/SpeedManiaModeCoverageBoostTest.java",
    ],
    "nullpomino/game/net/NetSPRankingPropertyEdgeCasesTest.java": [
        "nullpomino/game/net/NetSPRankingTest.java",
    ],
    "nullpomino/game/net/NetUtilProcessPacketBufferEdgeCasesTest.java": [
        "nullpomino/game/net/NetUtilRoundTripTest.java",
    ],
    "nullpomino/game/play/GameManagerExtraTest.java": [
        "nullpomino/game/play/GameManagerCommitHashEdgeTest.java",
    ],
    "nullpomino/game/randomizer/RandomizerBranchCoverageSweepTest.java": [
        "nullpomino/game/randomizer/RandomizerBranchTest.java",
    ],
    "nullpomino/gui/sdl/DummyMenuChooseStateSDLLogicTest.java": [
        "nullpomino/gui/sdl/DummyMenuChooseStateForwardTest.java",
        "nullpomino/gui/sdl/DummyMenuChooseStateJustEnteredTest.java",
    ],
    "nullpomino/gui/sdl/DummyMenuScrollStateSDLLogicTest.java": [
        "nullpomino/gui/sdl/DummyMenuScrollStateSDLTest.java",
    ],
    "nullpomino/gui/sdl/NullpoMinoSDLLogicTest.java": [
        "nullpomino/gui/sdl/NullpoMinoSDLHelpersTest.java",
        "nullpomino/gui/sdl/NullpoMinoSDLNavigationGuardsTest.java",
    ],
    "nullpomino/gui/sdl/RendererSDLLogicTest.java": [
        "nullpomino/gui/sdl/RendererSDLColorTest.java",
    ],
    "nullpomino/gui/sdl/SoundManagerSDLLogicTest.java": [
        "nullpomino/gui/sdl/SoundManagerSDLTest.java",
    ],
    "nullpomino/gui/sdl/StateInGameSDLLogicTest.java": [
        "nullpomino/gui/sdl/StateInGameReplayBackTest.java",
        "nullpomino/gui/sdl/StateInGameResultPageInputTest.java",
    ],
    "nullpomino/gui/sdl/StateReplaySelectSDLLogicTest.java": [
        "nullpomino/gui/sdl/StateReplaySelectSDLTest.java",
    ],
}

SELECT_CLASSES = {
    "nullpomino/game/ai/TSpinAIBranchCoverageTest3.java": [
        "nullpomino.game.ai.TSpinAIBranchCoverageTest2",
    ],
}

