package mu.nu.nullpo.testutil;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Properties;

import mu.nu.nullpo.util.ModeManager;

/**
 * Re-record the baseline snapshot for every replay under
 * src/test/resources/replay/ by running it through ReplayRunner and
 * writing the result to src/test/resources/expected/ mirroring the
 * input tree. Runs against the current working tree (not the runfiles
 * sandbox), so invoke this from the workspace root — e.g.
 *
 *   bazel run //src/test/java:BaselineRecorder
 *
 * which Bazel executes with BUILD_WORKING_DIRECTORY set to the repo.
 */
public final class BaselineRecorder {

	private static final Path REPLAY_ROOT = Paths.get("src/test/resources/replay");
	private static final Path EXPECTED_ROOT = Paths.get("src/test/resources/expected");

	public static void main(String[] args) throws Exception {
		String cwd = System.getenv("BUILD_WORKING_DIRECTORY");
		if (cwd != null) {
			System.setProperty("user.dir", cwd);
		}
		Path base = (cwd != null) ? Paths.get(cwd) : Paths.get("").toAbsolutePath();

		ModeManager modeManager = new ModeManager();
		try (BufferedReader r = new BufferedReader(new FileReader(base.resolve("config/list/mode.lst").toFile()))) {
			modeManager.loadGameModes(r);
		}

		int count = 0;
		Path replayRoot = base.resolve(REPLAY_ROOT);
		Path expectedRoot = base.resolve(EXPECTED_ROOT);
		count += recordDir(replayRoot, expectedRoot, modeManager);
		System.out.println("recorded " + count + " baseline snapshot(s)");
	}

	private static int recordDir(Path dir, Path expectedDir, ModeManager modeManager) throws IOException {
		if (!Files.isDirectory(dir)) return 0;
		int count = 0;
		try (DirectoryStream<Path> stream = Files.newDirectoryStream(dir)) {
			for (Path entry : stream) {
				if (Files.isDirectory(entry)) {
					count += recordDir(entry, expectedDir.resolve(entry.getFileName()), modeManager);
				} else if (entry.toString().endsWith(".rep")) {
					count += recordOne(entry, expectedDir, modeManager);
				}
			}
		}
		return count;
	}

	private static int recordOne(Path replay, Path expectedDir, ModeManager modeManager) throws IOException {
		try {
			ReplayRunner.Snapshot snap = ReplayRunner.run(replay, modeManager);
			Files.createDirectories(expectedDir);
			Path out = expectedDir.resolve(stripExt(replay.getFileName().toString()) + ".properties");
			Properties p = new Properties();
			p.setProperty("modeName", snap.modeName);
			p.setProperty("score", Integer.toString(snap.score));
			p.setProperty("lines", Integer.toString(snap.lines));
			p.setProperty("time", Integer.toString(snap.time));
			p.setProperty("level", Integer.toString(snap.level));
			p.setProperty("totalPieceLocked", Integer.toString(snap.totalPieceLocked));
			p.setProperty("simulatedFrames", Integer.toString(snap.simulatedFrames));
			try (java.io.OutputStream os = Files.newOutputStream(out)) {
				p.store(os, "baseline generated by BaselineRecorder — do not hand-edit");
			}
			System.out.println(replay + " -> " + out + " " + snap);
			return 1;
		} catch (Exception e) {
			System.err.println("FAILED " + replay + ": " + e);
			e.printStackTrace(System.err);
			return 0;
		}
	}

	private static String stripExt(String n) {
		int i = n.lastIndexOf('.');
		return i < 0 ? n : n.substring(0, i);
	}

	private BaselineRecorder() {
	}
}
