/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nuklear.swig;

public final class nk_button_behavior {
  public final static int NK_BUTTON_DEFAULT = 0;
  public final static int NK_BUTTON_REPEATER = NK_BUTTON_DEFAULT + 1;
}
