/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nuklear.swig;

public final class nk_command_type {
  public final static int NK_COMMAND_NOP = 0;
  public final static int NK_COMMAND_SCISSOR = NK_COMMAND_NOP + 1;
  public final static int NK_COMMAND_LINE = NK_COMMAND_SCISSOR + 1;
  public final static int NK_COMMAND_CURVE = NK_COMMAND_LINE + 1;
  public final static int NK_COMMAND_RECT = NK_COMMAND_CURVE + 1;
  public final static int NK_COMMAND_RECT_FILLED = NK_COMMAND_RECT + 1;
  public final static int NK_COMMAND_RECT_MULTI_COLOR = NK_COMMAND_RECT_FILLED + 1;
  public final static int NK_COMMAND_CIRCLE = NK_COMMAND_RECT_MULTI_COLOR + 1;
  public final static int NK_COMMAND_CIRCLE_FILLED = NK_COMMAND_CIRCLE + 1;
  public final static int NK_COMMAND_ARC = NK_COMMAND_CIRCLE_FILLED + 1;
  public final static int NK_COMMAND_ARC_FILLED = NK_COMMAND_ARC + 1;
  public final static int NK_COMMAND_TRIANGLE = NK_COMMAND_ARC_FILLED + 1;
  public final static int NK_COMMAND_TRIANGLE_FILLED = NK_COMMAND_TRIANGLE + 1;
  public final static int NK_COMMAND_POLYGON = NK_COMMAND_TRIANGLE_FILLED + 1;
  public final static int NK_COMMAND_POLYGON_FILLED = NK_COMMAND_POLYGON + 1;
  public final static int NK_COMMAND_POLYLINE = NK_COMMAND_POLYGON_FILLED + 1;
  public final static int NK_COMMAND_TEXT = NK_COMMAND_POLYLINE + 1;
  public final static int NK_COMMAND_IMAGE = NK_COMMAND_TEXT + 1;
}
