/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nuklear.swig;

public class nk_color {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected nk_color(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(nk_color obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(nk_color obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nuklearJNI.delete_nk_color(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setR(short value) {
    nuklearJNI.nk_color_r_set(swigCPtr, this, value);
  }

  public short getR() {
    return nuklearJNI.nk_color_r_get(swigCPtr, this);
  }

  public void setG(short value) {
    nuklearJNI.nk_color_g_set(swigCPtr, this, value);
  }

  public short getG() {
    return nuklearJNI.nk_color_g_get(swigCPtr, this);
  }

  public void setB(short value) {
    nuklearJNI.nk_color_b_set(swigCPtr, this, value);
  }

  public short getB() {
    return nuklearJNI.nk_color_b_get(swigCPtr, this);
  }

  public void setA(short value) {
    nuklearJNI.nk_color_a_set(swigCPtr, this, value);
  }

  public short getA() {
    return nuklearJNI.nk_color_a_get(swigCPtr, this);
  }

  public nk_color() {
    this(nuklearJNI.new_nk_color(), true);
  }

}
