/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nuklear.swig;

public final class nk_edit_events {
  public final static int NK_EDIT_ACTIVE = (1 << (0));
  public final static int NK_EDIT_INACTIVE = (1 << (1));
  public final static int NK_EDIT_ACTIVATED = (1 << (2));
  public final static int NK_EDIT_DEACTIVATED = (1 << (3));
  public final static int NK_EDIT_COMMITED = (1 << (4));
}
