/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nuklear.swig;

public class nk_image {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected nk_image(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(nk_image obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(nk_image obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nuklearJNI.delete_nk_image(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHandle(nk_handle value) {
    nuklearJNI.nk_image_handle_set(swigCPtr, this, nk_handle.getCPtr(value), value);
  }

  public nk_handle getHandle() {
    long cPtr = nuklearJNI.nk_image_handle_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nk_handle(cPtr, false);
  }

  public void setW(int value) {
    nuklearJNI.nk_image_w_set(swigCPtr, this, value);
  }

  public int getW() {
    return nuklearJNI.nk_image_w_get(swigCPtr, this);
  }

  public void setH(int value) {
    nuklearJNI.nk_image_h_set(swigCPtr, this, value);
  }

  public int getH() {
    return nuklearJNI.nk_image_h_get(swigCPtr, this);
  }

  public void setRegion(SWIGTYPE_p_unsigned_short value) {
    nuklearJNI.nk_image_region_set(swigCPtr, this, SWIGTYPE_p_unsigned_short.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_short getRegion() {
    long cPtr = nuklearJNI.nk_image_region_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
  }

  public nk_image() {
    this(nuklearJNI.new_nk_image(), true);
  }

}
