/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nuklear.swig;

public class nk_input {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected nk_input(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(nk_input obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(nk_input obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nuklearJNI.delete_nk_input(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setKeyboard(nk_keyboard value) {
    nuklearJNI.nk_input_keyboard_set(swigCPtr, this, nk_keyboard.getCPtr(value), value);
  }

  public nk_keyboard getKeyboard() {
    long cPtr = nuklearJNI.nk_input_keyboard_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nk_keyboard(cPtr, false);
  }

  public void setMouse(nk_mouse value) {
    nuklearJNI.nk_input_mouse_set(swigCPtr, this, nk_mouse.getCPtr(value), value);
  }

  public nk_mouse getMouse() {
    long cPtr = nuklearJNI.nk_input_mouse_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nk_mouse(cPtr, false);
  }

  public nk_input() {
    this(nuklearJNI.new_nk_input(), true);
  }

}
