/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nuklear.swig;

public class nk_mouse {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected nk_mouse(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(nk_mouse obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(nk_mouse obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nuklearJNI.delete_nk_mouse(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setButtons(nk_mouse_button value) {
    nuklearJNI.nk_mouse_buttons_set(swigCPtr, this, nk_mouse_button.getCPtr(value), value);
  }

  public nk_mouse_button getButtons() {
    long cPtr = nuklearJNI.nk_mouse_buttons_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nk_mouse_button(cPtr, false);
  }

  public void setPos(nk_vec2 value) {
    nuklearJNI.nk_mouse_pos_set(swigCPtr, this, nk_vec2.getCPtr(value), value);
  }

  public nk_vec2 getPos() {
    long cPtr = nuklearJNI.nk_mouse_pos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nk_vec2(cPtr, false);
  }

  public void setPrev(nk_vec2 value) {
    nuklearJNI.nk_mouse_prev_set(swigCPtr, this, nk_vec2.getCPtr(value), value);
  }

  public nk_vec2 getPrev() {
    long cPtr = nuklearJNI.nk_mouse_prev_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nk_vec2(cPtr, false);
  }

  public void setDelta(nk_vec2 value) {
    nuklearJNI.nk_mouse_delta_set(swigCPtr, this, nk_vec2.getCPtr(value), value);
  }

  public nk_vec2 getDelta() {
    long cPtr = nuklearJNI.nk_mouse_delta_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nk_vec2(cPtr, false);
  }

  public void setScroll_delta(float value) {
    nuklearJNI.nk_mouse_scroll_delta_set(swigCPtr, this, value);
  }

  public float getScroll_delta() {
    return nuklearJNI.nk_mouse_scroll_delta_get(swigCPtr, this);
  }

  public nk_mouse() {
    this(nuklearJNI.new_nk_mouse(), true);
  }

}
