/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nuklear.swig;

public final class nk_panel_flags {
  public final static int NK_WINDOW_BORDER = (1 << (0));
  public final static int NK_WINDOW_BORDER_HEADER = (1 << (1));
  public final static int NK_WINDOW_MOVABLE = (1 << (2));
  public final static int NK_WINDOW_SCALABLE = (1 << (3));
  public final static int NK_WINDOW_CLOSABLE = (1 << (4));
  public final static int NK_WINDOW_MINIMIZABLE = (1 << (5));
  public final static int NK_WINDOW_DYNAMIC = (1 << (6));
  public final static int NK_WINDOW_NO_SCROLLBAR = (1 << (7));
  public final static int NK_WINDOW_TITLE = (1 << (8));
}
