/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nuklear.swig;

public class nk_scroll {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected nk_scroll(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(nk_scroll obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(nk_scroll obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nuklearJNI.delete_nk_scroll(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(int value) {
    nuklearJNI.nk_scroll_x_set(swigCPtr, this, value);
  }

  public int getX() {
    return nuklearJNI.nk_scroll_x_get(swigCPtr, this);
  }

  public void setY(int value) {
    nuklearJNI.nk_scroll_y_set(swigCPtr, this, value);
  }

  public int getY() {
    return nuklearJNI.nk_scroll_y_get(swigCPtr, this);
  }

  public nk_scroll() {
    this(nuklearJNI.new_nk_scroll(), true);
  }

}
