/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nuklear.swig;

public final class nk_text_align {
  public final static int NK_TEXT_ALIGN_LEFT = 1;
  public final static int NK_TEXT_ALIGN_CENTERED = 2;
  public final static int NK_TEXT_ALIGN_RIGHT = 4;
  public final static int NK_TEXT_ALIGN_TOP = 8;
  public final static int NK_TEXT_ALIGN_MIDDLE = 16;
  public final static int NK_TEXT_ALIGN_BOTTOM = 32;
}
